const mongoose = require('mongoose');
const Book = require('./middleware/models/Book');
require('dotenv').config();

const sampleBooks = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "978-0-7432-7356-5",
    category: "Fiction",
    price: 12.99,
    description: "A classic American novel about the Jazz Age.",
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    inventory: 50,
    rating: 4.5,
    reviews: 1200
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    category: "Fiction",
    price: 11.99,
    description: "A powerful story of racial injustice and loss of innocence.",
    image: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    inventory: 45,
    rating: 4.8,
    reviews: 2500
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    category: "Non-Fiction",
    price: 16.99,
    description: "An exploration of how Homo sapiens came to dominate the world.",
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    inventory: 30,
    rating: 4.6,
    reviews: 1800
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "978-0-06-112241-5",
    category: "Fiction",
    price: 13.99,
    description: "A philosophical tale about following your dreams.",
    image: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    inventory: 60,
    rating: 4.4,
    reviews: 2200
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-0-13-235088-4",
    category: "Technology",
    price: 49.99,
    description: "A handbook of agile software craftsmanship.",
    image: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    inventory: 25,
    rating: 4.7,
    reviews: 1500
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "978-0-316-76948-0",
    category: "Fiction",
    price: 10.99,
    description: "A controversial novel about teenage rebellion.",
    image: "https://covers.openlibrary.org/b/isbn/9780316769480-L.jpg",
    inventory: 40,
    rating: 4.2,
    reviews: 1900
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "978-0-452-28423-4",
    category: "Fiction",
    price: 9.99,
    description: "A dystopian novel about totalitarianism.",
    image: "https://covers.openlibrary.org/b/isbn/9780452284234-L.jpg",
    inventory: 55,
    rating: 4.6,
    reviews: 3000
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbn: "978-1-4516-4853-9",
    category: "Biography",
    price: 17.99,
    description: "The exclusive biography of Apple's visionary founder.",
    image: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
    inventory: 35,
    rating: 4.5,
    reviews: 2100
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "978-0-85783-788-6",
    category: "Self-Help",
    price: 14.99,
    description: "Timeless lessons on wealth, greed, and happiness.",
    image: "https://covers.openlibrary.org/b/isbn/9780857837886-L.jpg",
    inventory: 28,
    rating: 4.7,
    reviews: 3200
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    isbn: "978-0-307-26975-1",
    category: "Mystery",
    price: 15.99,
    description: "A gripping mystery thriller.",
    image: "https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg",
    inventory: 42,
    rating: 4.3,
    reviews: 1700
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0-14-143951-8",
    category: "Romance",
    price: 8.99,
    description: "A classic romance novel.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    inventory: 38,
    rating: 4.5,
    reviews: 2400
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    isbn: "978-0-544-08710-3",
    category: "Fantasy",
    price: 24.99,
    description: "An epic fantasy trilogy.",
    image: "https://covers.openlibrary.org/b/isbn/9780544087103-L.jpg",
    inventory: 33,
    rating: 4.9,
    reviews: 2800
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0-553-10953-5",
    category: "Science",
    price: 13.99,
    description: "A journey into the nature of space and time.",
    image: "https://covers.openlibrary.org/b/isbn/9780553109535-L.jpg",
    inventory: 27,
    rating: 4.6,
    reviews: 1600
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    isbn: "978-1-937856-65-0",
    category: "History",
    price: 6.99,
    description: "An ancient Chinese military treatise.",
    image: "https://covers.openlibrary.org/b/isbn/9781937856650-L.jpg",
    inventory: 50,
    rating: 4.4,
    reviews: 1400
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "978-0-7352-1129-2",
    category: "Self-Help",
    price: 16.99,
    description: "An easy and proven way to build good habits.",
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    inventory: 40,
    rating: 4.8,
    reviews: 3500
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0-441-17271-9",
    category: "Science Fiction",
    price: 18.99,
    description: "An epic science fiction masterpiece set on the desert planet Arrakis.",
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    inventory: 36,
    rating: 4.7,
    reviews: 4200
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "978-0-544-08711-0",
    category: "Fantasy",
    price: 14.99,
    description: "A fantasy adventure about Bilbo Baggins and his unexpected journey.",
    image: "https://covers.openlibrary.org/b/isbn/9780544087110-L.jpg",
    inventory: 48,
    rating: 4.8,
    reviews: 3100
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    isbn: "978-0-385-50420-5",
    category: "Mystery",
    price: 13.99,
    description: "A thrilling mystery involving ancient secrets and religious conspiracies.",
    image: "https://covers.openlibrary.org/b/isbn/9780307277671-L.jpg",
    inventory: 52,
    rating: 4.2,
    reviews: 2800
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    isbn: "978-1-5011-9481-3",
    category: "Romance",
    price: 15.99,
    description: "A captivating story about a reclusive Hollywood icon and her mysterious life.",
    image: "https://covers.openlibrary.org/b/isbn/9781501139239-L.jpg",
    inventory: 29,
    rating: 4.6,
    reviews: 1900
  },
  {
    title: "Educated",
    author: "Tara Westover",
    isbn: "978-0-399-59050-4",
    category: "Biography",
    price: 16.99,
    description: "A memoir about a woman who grows up in a survivalist family and goes on to earn a PhD.",
    image: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    inventory: 31,
    rating: 4.7,
    reviews: 2300
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    isbn: "978-1-250-30169-7",
    category: "Mystery",
    price: 14.99,
    description: "A psychological thriller about a woman who refuses to speak after killing her husband.",
    image: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    inventory: 44,
    rating: 4.5,
    reviews: 2100
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    isbn: "978-0-593-09885-4",
    category: "Science Fiction",
    price: 17.99,
    description: "A lone astronaut must save the earth from disaster in this thrilling sci-fi adventure.",
    image: "https://covers.openlibrary.org/b/isbn/9780593098845-L.jpg",
    inventory: 37,
    rating: 4.8,
    reviews: 2600
  },
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    isbn: "978-0-525-55948-1",
    category: "Fiction",
    price: 15.99,
    description: "A novel about life, death, and the infinite possibilities in between.",
    image: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    inventory: 41,
    rating: 4.4,
    reviews: 1800
  },
  {
    title: "It Ends with Us",
    author: "Colleen Hoover",
    isbn: "978-1-5011-1036-8",
    category: "Romance",
    price: 13.99,
    description: "A heartbreaking and powerful novel about love and resilience.",
    image: "https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg",
    inventory: 46,
    rating: 4.6,
    reviews: 2400
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    isbn: "978-0-06-245771-4",
    category: "Self-Help",
    price: 15.99,
    description: "A counterintuitive approach to living a good life.",
    image: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    inventory: 33,
    rating: 4.3,
    reviews: 2700
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231611-0",
    category: "Non-Fiction",
    price: 17.99,
    description: "A graphic history of humankind's creation and evolution.",
    image: "https://covers.openlibrary.org/b/isbn/9780062316110-L.jpg",
    inventory: 28,
    rating: 4.5,
    reviews: 1400
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    isbn: "978-0-375-84220-7",
    category: "Fiction",
    price: 12.99,
    description: "A story set in Nazi Germany, told by Death itself.",
    image: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    inventory: 39,
    rating: 4.7,
    reviews: 2900
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "978-0-374-27563-1",
    category: "Non-Fiction",
    price: 16.99,
    description: "A groundbreaking tour of the mind and explains the two systems that drive the way we think.",
    image: "https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg",
    inventory: 26,
    rating: 4.6,
    reviews: 2000
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    isbn: "978-0-439-02348-1",
    category: "Science Fiction",
    price: 11.99,
    description: "A dystopian adventure where teens fight to the death in a televised spectacle.",
    image: "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
    inventory: 54,
    rating: 4.5,
    reviews: 3300
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    isbn: "978-1-59448-000-3",
    category: "Fiction",
    price: 13.99,
    description: "A powerful story of friendship, betrayal, and redemption set in Afghanistan.",
    image: "https://covers.openlibrary.org/b/isbn/9781594480003-L.jpg",
    inventory: 43,
    rating: 4.7,
    reviews: 2500
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    isbn: "978-1-57062-480-4",
    category: "Self-Help",
    price: 14.99,
    description: "A guide to spiritual enlightenment through living in the present moment.",
    image: "https://covers.openlibrary.org/b/isbn/9781570624804-L.jpg",
    inventory: 35,
    rating: 4.4,
    reviews: 2200
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbn: "978-0-307-58836-4",
    category: "Mystery",
    price: 14.99,
    description: "A psychological thriller about a marriage gone terribly wrong.",
    image: "https://covers.openlibrary.org/b/isbn/9780307588364-L.jpg",
    inventory: 38,
    rating: 4.3,
    reviews: 2100
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    isbn: "978-0-8041-3902-1",
    category: "Science Fiction",
    price: 15.99,
    description: "An astronaut stranded on Mars must survive using his wits and limited resources.",
    image: "https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg",
    inventory: 40,
    rating: 4.7,
    reviews: 2800
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    isbn: "978-1-61268-018-7",
    category: "Self-Help",
    price: 13.99,
    description: "What the rich teach their kids about money that the poor and middle class do not.",
    image: "https://covers.openlibrary.org/b/isbn/9781612680187-L.jpg",
    inventory: 47,
    rating: 4.2,
    reviews: 1900
  },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    isbn: "978-0-06-119900-4",
    category: "Fantasy",
    price: 19.99,
    description: "A magical journey into the land of Narnia where animals talk and magic exists.",
    image: "https://covers.openlibrary.org/b/isbn/9780061199004-L.jpg",
    inventory: 32,
    rating: 4.6,
    reviews: 2700
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "978-0-06-085052-4",
    category: "Science Fiction",
    price: 10.99,
    description: "A dystopian novel about a future society controlled by technology and conditioning.",
    image: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    inventory: 45,
    rating: 4.5,
    reviews: 2300
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    isbn: "978-0-14-143957-0",
    category: "Fiction",
    price: 9.99,
    description: "A philosophical novel about vanity, youth, and the pursuit of beauty.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    inventory: 36,
    rating: 4.4,
    reviews: 1700
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    isbn: "978-1-4000-5217-2",
    category: "Biography",
    price: 15.99,
    description: "The story of how one woman's cells changed medical science forever.",
    image: "https://covers.openlibrary.org/b/isbn/9781400052172-L.jpg",
    inventory: 30,
    rating: 4.6,
    reviews: 1600
  },
  {
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    isbn: "978-0-385-49081-5",
    category: "Fiction",
    price: 13.99,
    description: "A dystopian novel about a totalitarian society where women are subjugated.",
    image: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    inventory: 34,
    rating: 4.6,
    reviews: 2400
  },
  {
    title: "The Design of Everyday Things",
    author: "Don Norman",
    isbn: "978-0-465-06710-7",
    category: "Technology",
    price: 18.99,
    description: "A guide to understanding good design and why some products work better than others.",
    image: "https://covers.openlibrary.org/b/isbn/9780465067107-L.jpg",
    inventory: 22,
    rating: 4.5,
    reviews: 1300
  },
  {
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-246431-6",
    category: "Non-Fiction",
    price: 17.99,
    description: "A brief history of tomorrow, exploring humanity's future.",
    image: "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
    inventory: 27,
    rating: 4.5,
    reviews: 1500
  },
  {
    title: "The Tipping Point",
    author: "Malcolm Gladwell",
    isbn: "978-0-316-31696-2",
    category: "Non-Fiction",
    price: 15.99,
    description: "How little things can make a big difference.",
    image: "https://covers.openlibrary.org/b/isbn/9780316316962-L.jpg",
    inventory: 31,
    rating: 4.4,
    reviews: 1800
  },
  {
    title: "The Extraordinary Adventure of Jai Santhosh",
    author: "Jai Santhosh",
    isbn: "978-0-1234-5678-9",
    category: "Fiction",
    price: 19.99,
    description: "An epic tale of adventure, discovery, and self-realization. Follow Jai Santhosh as he embarks on an extraordinary journey filled with mystery, courage, and unexpected twists. This captivating story takes readers through fantastical lands, challenging obstacles, and profound revelations that will inspire and enthrall. A must-read adventure that combines thrilling action with deep personal growth.",
    image: "https://covers.openlibrary.org/b/isbn/9780061199004-L.jpg",
    inventory: 50,
    rating: 5.0,
    reviews: 1250
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    isbn: "978-0-7564-0407-9",
    category: "Fantasy",
    price: 16.99,
    description: "A tale of magic, music, and mystery. Follow Kvothe as he recounts his legendary journey from humble beginnings to becoming the most notorious wizard his world has ever seen.",
    image: "https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg",
    inventory: 38,
    rating: 4.8,
    reviews: 3200
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    isbn: "978-0-525-47881-2",
    category: "Romance",
    price: 12.99,
    description: "A heart-wrenching love story about two teenagers who meet in a cancer support group. Despite their circumstances, they find love, hope, and meaning in their journey together.",
    image: "https://covers.openlibrary.org/b/isbn/9780525478812-L.jpg",
    inventory: 45,
    rating: 4.6,
    reviews: 2800
  },
  {
    title: "The Shining",
    author: "Stephen King",
    isbn: "978-0-385-12167-5",
    category: "Mystery",
    price: 14.99,
    description: "A psychological horror masterpiece about a writer who becomes the winter caretaker of an isolated hotel, where supernatural forces begin to influence his sanity.",
    image: "https://covers.openlibrary.org/b/isbn/9780385121675-L.jpg",
    inventory: 42,
    rating: 4.7,
    reviews: 2600
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "978-0-307-88789-4",
    category: "Technology",
    price: 18.99,
    description: "A revolutionary approach to business that's being adopted around the world. Learn how to build a sustainable business through continuous innovation and validated learning.",
    image: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    inventory: 33,
    rating: 4.5,
    reviews: 1900
  },
  {
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    isbn: "978-0-345-44774-3",
    category: "Biography",
    price: 13.99,
    description: "The first of Maya Angelou's seven autobiographies, recounting her childhood and early adult years, a story of strength, love, and perseverance.",
    image: "https://covers.openlibrary.org/b/isbn/9780345447743-L.jpg",
    inventory: 36,
    rating: 4.8,
    reviews: 2100
  },
  {
    title: "The Road",
    author: "Cormac McCarthy",
    isbn: "978-0-307-38789-9",
    category: "Fiction",
    price: 11.99,
    description: "A post-apocalyptic tale of a father and son's journey through a desolate America, maintaining their humanity in a world without hope.",
    image: "https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg",
    inventory: 40,
    rating: 4.4,
    reviews: 2400
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    isbn: "978-0-19-857519-1",
    category: "Science",
    price: 15.99,
    description: "A groundbreaking exploration of evolution from the gene's perspective, explaining how natural selection works at the most fundamental level.",
    image: "https://covers.openlibrary.org/b/isbn/9780198575191-L.jpg",
    inventory: 28,
    rating: 4.6,
    reviews: 1800
  },
  {
    title: "The Maze Runner",
    author: "James Dashner",
    isbn: "978-0-385-73794-4",
    category: "Science Fiction",
    price: 12.99,
    description: "When Thomas wakes up in the lift, the only thing he can remember is his name. He's surrounded by strangers in a place called the Glade, surrounded by massive walls that protect them from the maze.",
    image: "https://covers.openlibrary.org/b/isbn/9780385737944-L.jpg",
    inventory: 47,
    rating: 4.3,
    reviews: 2200
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    isbn: "978-0-14-028019-7",
    category: "Self-Help",
    price: 17.99,
    description: "A practical guide for anyone who wants power, observes power, or wants to arm themselves against power. Drawing on examples from history.",
    image: "https://covers.openlibrary.org/b/isbn/9780140280197-L.jpg",
    inventory: 35,
    rating: 4.4,
    reviews: 2500
  },
  {
    title: "The Color Purple",
    author: "Alice Walker",
    isbn: "978-0-15-602835-6",
    category: "Fiction",
    price: 13.99,
    description: "A powerful novel about the lives of African American women in the rural South, told through letters and focusing on themes of racism, sexism, and empowerment.",
    image: "https://covers.openlibrary.org/b/isbn/9780156028356-L.jpg",
    inventory: 39,
    rating: 4.7,
    reviews: 2700
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    isbn: "978-0-345-39180-3",
    category: "Science Fiction",
    price: 10.99,
    description: "A comedic science fiction series following the misadventures of Arthur Dent after Earth is demolished to make way for a hyperspace bypass.",
    image: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
    inventory: 52,
    rating: 4.6,
    reviews: 3300
  },
  {
    title: "The Help",
    author: "Kathryn Stockett",
    isbn: "978-0-425-23220-0",
    category: "Fiction",
    price: 14.99,
    description: "Set in Mississippi during the 1960s, this novel tells the story of African American maids working in white households and a young writer who breaks social conventions.",
    image: "https://covers.openlibrary.org/b/isbn/9780425232200-L.jpg",
    inventory: 41,
    rating: 4.5,
    reviews: 2900
  },
  {
    title: "A Brief History of Everything",
    author: "Bill Bryson",
    isbn: "978-0-7679-0817-4",
    category: "Non-Fiction",
    price: 15.99,
    description: "A journey through the most important scientific discoveries and theories that have shaped our understanding of the universe and life itself.",
    image: "https://covers.openlibrary.org/b/isbn/9780767908174-L.jpg",
    inventory: 30,
    rating: 4.6,
    reviews: 1600
  },
  {
    title: "The Time Machine",
    author: "H.G. Wells",
    isbn: "978-0-14-143997-6",
    category: "Science Fiction",
    price: 9.99,
    description: "A pioneering science fiction novel about a time traveler who journeys to the year 802,701 and encounters two distinct human species.",
    image: "https://covers.openlibrary.org/b/isbn/9780141439976-L.jpg",
    inventory: 44,
    rating: 4.3,
    reviews: 2000
  },
  {
    title: "The Bell Jar",
    author: "Sylvia Plath",
    isbn: "978-0-06-083702-0",
    category: "Fiction",
    price: 11.99,
    description: "A semi-autobiographical novel about a young woman's descent into mental illness, exploring themes of identity, depression, and societal expectations.",
    image: "https://covers.openlibrary.org/b/isbn/9780060837020-L.jpg",
    inventory: 37,
    rating: 4.5,
    reviews: 2300
  },
  {
    title: "The War of the Worlds",
    author: "H.G. Wells",
    isbn: "978-0-451-52530-1",
    category: "Science Fiction",
    price: 10.99,
    description: "A classic science fiction novel about a Martian invasion of Earth, exploring themes of imperialism and survival.",
    image: "https://covers.openlibrary.org/b/isbn/9780451525301-L.jpg",
    inventory: 43,
    rating: 4.4,
    reviews: 1900
  },
  {
    title: "The Giver",
    author: "Lois Lowry",
    isbn: "978-0-547-68742-0",
    category: "Fiction",
    price: 12.99,
    description: "A dystopian novel about a boy who lives in a seemingly perfect community where there is no pain, war, or suffering, but also no memories.",
    image: "https://covers.openlibrary.org/b/isbn/9780547687420-L.jpg",
    inventory: 46,
    rating: 4.7,
    reviews: 3100
  },
  {
    title: "The Outsiders",
    author: "S.E. Hinton",
    isbn: "978-0-14-240733-2",
    category: "Fiction",
    price: 10.99,
    description: "A coming-of-age novel about Ponyboy Curtis and his struggle with right and wrong in a society in which he believes he is an outsider.",
    image: "https://covers.openlibrary.org/b/isbn/9780142407332-L.jpg",
    inventory: 48,
    rating: 4.6,
    reviews: 2600
  },
  {
    title: "The Metamorphosis",
    author: "Franz Kafka",
    isbn: "978-0-14-310524-4",
    category: "Fiction",
    price: 9.99,
    description: "A novella about Gregor Samsa, a traveling salesman who wakes up one morning to find himself transformed into a giant insect.",
    image: "https://covers.openlibrary.org/b/isbn/9780143105244-L.jpg",
    inventory: 35,
    rating: 4.3,
    reviews: 1700
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    isbn: "978-0-307-23764-5",
    category: "Fantasy",
    price: 15.99,
    description: "A magical competition between two illusionists set in a mysterious circus that only opens at night, where reality and illusion blend together.",
    image: "https://covers.openlibrary.org/b/isbn/9780307237645-L.jpg",
    inventory: 34,
    rating: 4.5,
    reviews: 2400
  },
  {
    title: "The Stand",
    author: "Stephen King",
    isbn: "978-0-385-12168-2",
    category: "Fiction",
    price: 16.99,
    description: "A post-apocalyptic horror/fantasy novel about a pandemic of a weaponized strain of influenza that kills almost the entire world population.",
    image: "https://covers.openlibrary.org/b/isbn/9780385121682-L.jpg",
    inventory: 38,
    rating: 4.6,
    reviews: 2800
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "978-0-316-76948-1",
    category: "Fiction",
    price: 10.99,
    description: "A coming-of-age story about teenage rebellion and alienation in post-World War II America.",
    image: "https://covers.openlibrary.org/b/isbn/9780316769481-L.jpg",
    inventory: 55,
    rating: 4.2,
    reviews: 1900
  },
  {
    title: "The Seven Habits of Highly Effective People",
    author: "Stephen R. Covey",
    isbn: "978-0-671-70863-4",
    category: "Self-Help",
    price: 16.99,
    description: "A business and self-help book presenting a principle-centered approach for solving personal and professional problems.",
    image: "https://covers.openlibrary.org/b/isbn/9780671708634-L.jpg",
    inventory: 32,
    rating: 4.5,
    reviews: 2700
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    isbn: "978-0-14-044926-6",
    category: "Fiction",
    price: 14.99,
    description: "An adventure novel about a man who is wrongfully imprisoned and seeks revenge against those who betrayed him, set in France, Italy, and islands in the Mediterranean.",
    image: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    inventory: 36,
    rating: 4.7,
    reviews: 2100
  },
  {
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    isbn: "978-1-59463-366-9",
    category: "Mystery",
    price: 14.99,
    description: "A psychological thriller about a woman who becomes entangled in a missing persons investigation that sends her into a web of lies and deceit.",
    image: "https://covers.openlibrary.org/b/isbn/9781594633669-L.jpg",
    inventory: 40,
    rating: 4.2,
    reviews: 2300
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/bookstore');
    console.log('Connected to MongoDB');

    // Clear existing books
    await Book.deleteMany({});
    console.log('Cleared existing books');

    // Insert sample books
    await Book.insertMany(sampleBooks);
    console.log(`Seeded ${sampleBooks.length} books successfully`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();

